set(_CATKIN_CURRENT_PACKAGE "track_icp")
set(track_icp_VERSION "0.0.0")
set(track_icp_MAINTAINER "lbh <lbh@todo.todo>")
set(track_icp_PACKAGE_FORMAT "1")
set(track_icp_BUILD_DEPENDS "roscpp" "std_msgs")
set(track_icp_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(track_icp_BUILDTOOL_DEPENDS "catkin")
set(track_icp_BUILDTOOL_EXPORT_DEPENDS )
set(track_icp_EXEC_DEPENDS "roscpp" "std_msgs")
set(track_icp_RUN_DEPENDS "roscpp" "std_msgs")
set(track_icp_TEST_DEPENDS )
set(track_icp_DOC_DEPENDS )
set(track_icp_DEPRECATED "")